// Code generated by MockGen. DO NOT EDIT.
// Source: pornhub.go

// Package pornhub is a generated GoMock package.
package pornhub

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPornhub is a mock of Pornhub interface
type MockPornhub struct {
	ctrl     *gomock.Controller
	recorder *MockPornhubMockRecorder
}

// MockPornhubMockRecorder is the mock recorder for MockPornhub
type MockPornhubMockRecorder struct {
	mock *MockPornhub
}

// NewMockPornhub creates a new mock instance
func NewMockPornhub(ctrl *gomock.Controller) *MockPornhub {
	mock := &MockPornhub{ctrl: ctrl}
	mock.recorder = &MockPornhubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPornhub) EXPECT() *MockPornhubMockRecorder {
	return m.recorder
}

// GetThumbnailURLs mocks base method
func (m *MockPornhub) GetThumbnailURLs(videoURL string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnailURLs", videoURL)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnailURLs indicates an expected call of GetThumbnailURLs
func (mr *MockPornhubMockRecorder) GetThumbnailURLs(videoURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnailURLs", reflect.TypeOf((*MockPornhub)(nil).GetThumbnailURLs), videoURL)
}
